name: Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging


jobs:
  push_to_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cleanup 
      # Push to production

      - name: 🧐 Check for index.html
        run: |
          # ------------
          # Ensure files
          # ------------

          declare -a missing
          
          if ! [[ -f "index.html" ]]; then
            echo "Missing: index.html"
            exit 1
          else
            exit 0
          fi
  
      - name: Create .nojekyll file to avoid problems with CSS
        run: touch .nojekyll

      - name: 🚠 Push to production
        uses: EndBug/add-and-commit@v9
        with:
          message: Deploying build
          add: '.'
          push: origin HEAD:production --force

